"""
gitswap/ui/installer.py
-----------------------
Installs the `gitSwap` shell wrapper to a directory on the user's PATH.

The wrapper is a tiny bash script that forwards all arguments to the CLI's
`swap` subcommand, so the user can type:

    gitSwap              →  python3 git_identity_switcher.py swap
    gitSwap work         →  python3 git_identity_switcher.py swap work
    gitSwap personal     →  python3 git_identity_switcher.py swap personal

Install logic
-------------
1. Try /usr/local/bin first (standard; writable on most macOS + Homebrew setups).
2. Fall back to ~/.local/bin (always writable, no sudo required).
3. When using the fallback, automatically add it to the user's shell rc file
   (~/.zshrc, ~/.bash_profile, or ~/.bashrc) so it is on PATH in new terminals.
   This write is idempotent — the line is only appended if not already present.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from gitswap.constants import INSTALL_DIRS


def _detect_shell_rc() -> Path | None:
    """
    Return the rc/profile file for the user's current shell.
    Returns None if the shell is not recognised.
    """
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return Path.home() / ".zshrc"
    if "bash" in shell:
        # macOS bash uses .bash_profile for login shells by convention.
        bp = Path.home() / ".bash_profile"
        return bp if bp.exists() else Path.home() / ".bashrc"
    return None


def _ensure_dir_in_path(directory: Path) -> str:
    """
    Append `export PATH="<directory>:$PATH"` to the shell rc file, unless
    `directory` is already mentioned there.

    Returns a human-readable status string describing what happened.
    """
    rc = _detect_shell_rc()
    if rc is None:
        return (
            f"Unknown shell — add this to your shell rc manually:\n"
            f'  export PATH="{directory}:$PATH"'
        )

    existing = rc.read_text() if rc.exists() else ""
    if str(directory) in existing:
        return f"{directory} is already in {rc.name}"

    line = f'export PATH="{directory}:$PATH"'
    with rc.open("a") as fh:
        fh.write(f"\n# Added by Git-Swap\n{line}\n")

    return f"Added {directory} to ~/{rc.name} — run:  source ~/{rc.name}"


def install_gitswap(
    alias: str,
    cli_script: Path,
    python_exe: str = sys.executable,
) -> tuple[bool, str]:
    """
    Write a shell wrapper named `alias` to the first writable install directory.

    Args:
        alias:      The command name (e.g. "gitSwap").
        cli_script: Absolute path to git_identity_switcher.py.
        python_exe: Python interpreter to embed in the script (default: current).

    Returns:
        (success, message) — message describes where the script was installed
        or explains why installation failed.
    """
    script_content = (
        f"#!/bin/bash\n"
        f"# {alias} — swap Git identity for the current repo\n"
        f"# Generated by Git-Swap  ({_REPO_URL})\n"
        f'"{python_exe}" "{cli_script}" swap "$@"\n'
    )

    for install_dir in INSTALL_DIRS:
        try:
            install_dir.mkdir(parents=True, exist_ok=True)
            target = install_dir / alias
            target.write_text(script_content)
            target.chmod(0o755)

            # /usr/local/bin is typically already on PATH — no rc patching needed.
            if install_dir == INSTALL_DIRS[0]:
                return True, str(target)

            # Fallback directory: patch PATH in the shell rc.
            path_msg = _ensure_dir_in_path(install_dir)
            return True, f"Installed to {target}\n{path_msg}"

        except PermissionError:
            continue   # try the next directory

    return False, (
        f"Could not write to {INSTALL_DIRS[0]} or {INSTALL_DIRS[1]}.\n"
        "Try:  sudo chmod o+w /usr/local/bin"
    )


_REPO_URL = "https://github.com/feanor08/Git-Swap"
